from dataclasses import asdict, dataclass
import json
from pathlib import Path

from cccagents.complexity_classifier import classify_project_request
from cccagents.project_state import ProjectState, save_project_state
from cccagents.role_plan import RolePlan, RoleTask, build_role_plan


@dataclass(frozen=True)
class OrchestrationRequest:
    project_id: str
    text: str
    project_root: Path
    now: str


@dataclass(frozen=True)
class ExecutionResult:
    role: str
    template: str
    artifact_paths: list[Path]
    passed: bool
    issues: list[str]


@dataclass(frozen=True)
class OrchestrationResult:
    project_id: str
    status: str
    complexity: str
    executed_roles: list[str]
    issues: list[str]


class FakeExecutor:
    def run(self, project_dir: Path, task: RoleTask) -> ExecutionResult:
        artifact_paths: list[Path] = []
        for relative in task.expected_artifacts:
            path = project_dir / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(f"# {task.role} {task.template}\n\nGenerated by fake executor.\n", encoding="utf-8")
            artifact_paths.append(path)
        return ExecutionResult(
            role=task.role,
            template=task.template,
            artifact_paths=artifact_paths,
            passed=True,
            issues=[],
        )


def orchestrate_request(request: OrchestrationRequest, executor: FakeExecutor) -> OrchestrationResult:
    decision = classify_project_request(request.text)
    plan = build_role_plan(decision)
    project_dir = request.project_root / request.project_id
    project_dir.mkdir(parents=True, exist_ok=True)
    _save_initial_state(request, decision.complexity, decision.required_roles, decision.risk_flags, "running")

    executed_roles: list[str] = []
    issues: list[str] = []
    for phase in plan.phases:
        for task in phase.tasks:
            result = executor.run(project_dir, task)
            executed_roles.append(result.role)
            issues.extend(result.issues)
            if not result.passed:
                _save_initial_state(request, decision.complexity, decision.required_roles, decision.risk_flags, "blocked")
                return OrchestrationResult(request.project_id, "blocked", decision.complexity, executed_roles, issues)

    _save_initial_state(request, decision.complexity, decision.required_roles, decision.risk_flags, "done")
    return OrchestrationResult(request.project_id, "done", decision.complexity, executed_roles, issues)


def _save_initial_state(
    request: OrchestrationRequest,
    complexity: str,
    required_roles: list[str],
    risk_flags: list[str],
    status: str,
) -> None:
    save_project_state(
        request.project_root / request.project_id,
        ProjectState(
            project_id=request.project_id,
            source="feishu",
            status=status,
            complexity=complexity,
            current_phase="DONE" if status == "done" else "RUNNING",
            required_roles=required_roles,
            risk_flags=risk_flags,
            approval_policy="auto_if_l0_l1_and_all_reviews_pass",
            retry_count_by_phase={},
            created_at=request.now,
            updated_at=request.now,
            last_pm_notification_at=None,
        ),
    )
